services:

  # Prefect Database
  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    profiles: ["server"]

  # MinIO for flow storage
  minio:
    image: minio/minio:latest
    entrypoint: ["minio", "server", "--address", "0.0.0.0:9000", "--console-address", "0.0.0.0:9001", "/data"]
    volumes:
      - "minio:/data"
    ports:
      - 9000:9000
      - 9001:9001
    profiles: ["minio"]

  # Prefect Server API and UI
  server:
    image: prefecthq/prefect:2.11.5-python3.11
    restart: always
    volumes:
      - prefect:/root/.prefect
      - ./config:/usr/app/config  # Mount config folder for credentials
      - ./config/service_account.json:/usr/app/service_account.json
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      - PREFECT_UI_URL=http://127.0.0.1:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
      - GOOGLE_APPLICATION_CREDENTIALS=/config/service_account.json
    ports:
      - 4200:4200
    depends_on:
      - database
    profiles: ["server"]

  # Prefect Agent
  agent:
    image: prefecthq/prefect:2.11.5-python3.11
    restart: always
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "agent", "start", "-q", "YOUR_WORK_QUEUE_NAME"]
    environment:
      - PREFECT_API_URL=http://server:4200/api
    profiles: ["agent"]
    volumes:
      - ./config:/usr/app/config  # Mount config folder for credentials

  # Prefect CLI
  cli:
    image: prefecthq/prefect:2.11.5-python3.11
    entrypoint: "bash"
    working_dir: "/root/flows"
    volumes:
      - "./flows:/root/flows"
      - ./config:/usr/app/config  # Mount config folder for credentials
    environment:
      - PREFECT_API_URL=http://server:4200/api
    profiles: ["cli"]

volumes:
  prefect:
  db:
  minio:

networks:
  default:
    name: prefect-network
